**Theoretical Questions**

Q.1 Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Ans. NumPy, short for "Numerical Python," is essentially a core library in Python uniquely developed for efficient numerical computations, with large datasets, making it the foundation of scientific computing and data analysis by offering high-performance multi-dimensional arrays and a wide range of mathematical functions, greatly extending Python's capability for numerical operations, increasing speed, optimized usage of memory compared to standard Python lists.


**Key advantages of NumPy:**

1.Speed and Efficiency:

NumPy arrays are implemented in C; therefore, operations on them are much faster than using standard Python lists-very significant performance differences when dealing with large datasets and complex calculations.

2.Efficiency Memory:

They store data in contiguous blocks of memory, which allows for fewer overheads and much better memory usage than Python lists.

3.Vectorized Operations:

NumPy achieves element-wise operations across entire arrays, obliterating the need for explicit loops in code and thereby providing a concise, efficient way to achieve complex mathematical computations.

4.Broadcasting:

NumPy's broadcasting feature enables operations between arrays of different shapes, simplifying data manipulation and reducing the need for manual looping.

5.Precise Mathematical Functionality:

NumPy provides an array of mathematical functions including linear algebra operations, trigonometric functions, statistical calculations, among many others that can be applied directly to the arrays.

6.Integration with other libraries:

It combines quite well with other scientific Python libraries like SciPy, Matplotlib for advanced mathematical functions and visualization, and Pandas for further data analysis, thereby making an amazing data science ecosystem.

**How NumPy Improves Python for Numerical Computation**

1.Handling High-Dimensional Datasets:

NumPy arrays are optimized for handling large datasets efficiently, making it ideal for scientific computing tasks that involve complex calculations on large volumes of data.

2.Simplified Code:

NumPy allows the possibility to write compact, readable code by providing vectorized operations in such a way that explicit loops are avoided in most cases.

3.Skill Boost:

The use of NumPy arrays also has its underlying C implementation to attain tremendous speedup over standard Python lists for numerical computations.

**Example Use Cases:**

1.Calculation of descriptive statistics, such as mean, standard deviation, and variance, on a large dataset.

2.Implement matrix operations to the neural network, play around with array format of training data.

3.Signal Processing: Fourier transforms for signal analysis
Scientific modeling: From solving differential equations to doing complex simulations.

In a word, NumPy is that critical piece of science and data processing in Python that brings inside powerful and efficient ways to conduct numeric operations on large-size data to serve as a cornerstone of many applications for data science and machine learning.

Q.2 Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Ans. **np.mean() vs np.average() in NumPy**


`np.mean()` and `np.average()` are two functions in NumPy that compute the average of an array. They present two different functionalities as well as types of averages.

**np.mean()**


Purpose: Calculates the arithmetic mean of an array.
Functionality:
It accepts an array.
It calculates the summation of all elements of the array.
- It goes ahead to divide the sum by the number of elements to get the arithmetic mean.
- Optionally: specify an axis on which the mean should be computed.
- Optionally, pass an axis along which to compute.

 **np.average()**

 It can calculate both arithmetic and weighted averages
 Functions
 - accepts any array and an optional `weights` array
 - If `weights` are not specified, it returns the arithmetic mean just like  `np.mean()`.
- If `weights` is given, it returns the weighted average:
 ```
    weighted_average = (sum(x * w)) / sum(w)
    ```
 - Optionally, one can also specify an axis to compute the mean along a particular axis.

**Differences in Function:**

Feature np.mean() np.average()

**Average Type** Arithmetic mean Arithmetic or weighted average
| Supports Weights | Does not support weights |

**Flexibility** | Less Flexible | More Flexible |

**When to Use Which:**

* **np.mean()**: Use this function if you require simple arithmetic mean computation for an array
* **np.average()**: Use this function if you require weighted average computations or if some flexibility is required in computing different averages.



# Using np.mean() for calculating mean value
mean_value = np.mean(arr)
print("Mean Value:", mean_value)

# Using np.average() to calculate weighted average
weights = np.array([1, 2, 3, 4, 5])
weighted_mean = np.average(arr, weights=weights)
print("Weighted Mean:", weighted_mean)
END




In [ ]:
#Example
import numpy as np

# Sample array
arr = np.array([1, 2, 3, 4, 5])

# Arithmetic mean using np.mean()
mean_value = np.mean(arr)
print("Arithmetic mean:", mean_value)

# Weighted average using np.average()
weights = np.array([1, 2, 3, 4, 5])
weighted_mean = np.average(arr, weights=weights)
print("Weighted mean:", weighted_mean)

Arithmetic mean: 3.0
Weighted mean: 3.6666666666666665


In conclusion, it appears that both functions can be used to calculate the average of an array, but `np.average()` provides flexibility in that it can compute weighted averages. Use whichever function fits your needs and the kind of average you would like to calculate.

Q.3 Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Ans. Reversing NumPy Arrays Along Different Axes

NumPy provides efficient methods to reverse along specified axes in arrays. This is one of the very basic operations and is used extensively in all data manipulation operations, from image processing, signal processing, and machine learning, among others.

**1.Reversing a 1D Array**

To reverse a 1D array, we can simply use the [::-1] slicing syntax:


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)  # Output: [5 4 3 2 1]

[5 4 3 2 1]


**2.Reversing a 2D Array**

For 2D arrays, we can reverse along rows or columns using the [::-1] slicing:

Reversing rows:

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

reversed_rows = arr[::-1, :]
print(reversed_rows)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


Reversing columns:

In [ ]:
reversed_cols = arr[:, ::-1]
print(reversed_cols)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


Reversing both rows and columns:

In [ ]:
reversed_both = arr[::-1, ::-1]
print(reversed_both)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


General Approach for Higher-Dimensional Arrays:

For higher-dimensional arrays, we can use the np.flip() function, which takes an array and an axis as input:

In [ ]:
arr = np.random.rand(3, 4, 2)

# Reversing along the first axis (rows)
reversed_first_axis = np.flip(arr, axis=0)

# Reversing along the second axis (columns)
reversed_second_axis = np.flip(arr, axis=1)

# Reversing along the last axis
reversed_last_axis = np.flip(arr, axis=-1)

Key Takeaways:

1.The slicing[::-1] is the concise version of reversing arrays.

2.Using np.flip() offers much greater flexibility, especially for higher dimensional arrays.

3.When applying np.flip(), you specify axes along which to reverse the array using the axis parameter.

4.Negative indices may be used to indicate axes from the end. For example, axis=-1 refers to the last axis.

5.With a good feel for these methods, you can sort most mundane things in NumPy arrays to your whims.


Q.4  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

Ans. Determining Data Types in NumPy Arrays

In NumPy, you can determine the data type of elements in an array using the dtype attribute. Here's a simple example:

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Print the data type
print(arr.dtype)

int64


Importance of Data Type in Memory Management and Performance

Data types are important for memory management as well as performance optimization in NumPy arrays:

Memory Efficiency

1.Smaller data types mean less memory: You can significantly reduce the amount of memory consumed by your arrays when you make the proper choice of data type. For example, half of the memory used by an integer array is consumed when you use int32 instead of int64.

2.Efficient Memory Allocation: NumPy stores arrays in contiguous memory blocks, thus making memory access and cache usage efficient.

Performance Optimization:

1.Hardware-Oriented Operations: Many modern processors are optimized for specific data types. Code which uses the most appropriate data type can see incredible performance boosts.

2.Vectorized Operations: The vectorized operations of NumPy are very efficient, especially with homogeneous data types. This accelerates computations and reduces overhead.

3.Memory Bandwidth: The data type for the smaller data types can be moved between memory and the processor with lower memory bandwidth, and it generally improves performance.

Precision and Range:

1.Select the Appropriate Precision: Select the data type such that you get enough precision for representing your data, but lose no information.

Important Factors:

For a particular problem, you can avoid overflows and underflows by getting a feel for the range of a data type.

Default Data Types. NumPy data types are automatically inferred from the input data in most circumstances. Be careful of this automatic type deduction because it can result in inconsistent data types in certain situations.

Explicit Data Type Specification. Data types can be explicitly declared at array creation time using the dtype argument. This allows for fine-grained tuning of memory usage and performance.

Data Type Casting: You can perform data type casting using the astype method if that is required. However, remember that data type casting can suffer from potential precision loss as well as give overflows.

So, if you think about data types carefully, you can build high-performance and efficient NumPy arrays that will simply solve your data analysis and scientific computing tasks effectively.


Q.5 Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans.**NumPy ndarrays: A Powerful Tool for Numerical Computing**

Numerical computations using scientific computing and data analysis with Python are quite popular, and `ndarray` (n-dimensional array) of NumPy becomes the heart of this computation. The n-dimensional arrays offer highly efficient storage and manipulation of large datasets, making them indispensable for various numerical computations.

**Key Features of Numpy ndarrays:**

1.  **Multidimensional Arrays:**
The most important feature is that ndarrays can be used for several different dimensions, from very simple one-dimensional vectors to rather more complex multidimensional matrices and even tensors. That means diverse data structures can be used.

2. **Uniform Data Type:**
   Every element in the ndarray is of the same data type for efficient usage of memory along with optimized operations.

3. **Efficient Memory Layout:
 - `ndarrays` are stored as blocks in contiguous memory space; that's why access, especially manipulation of elements is very fast.

4. **Vectorized Operations:**
   - Vectorized operations in NumPy allow you to apply mathematical functions on entire arrays element-wise, hence speeding up computations by several orders of magnitude compared to traditional loops in Python.

5. **Broadcasting:**
 - Broadcasting is a very powerful technique to perform arithmetic operations between arrays of quite different shapes as long as certain rules are met, and this really simplifies lots of common operations.

6. **Indexing and Slicing:**
 - `ndarrays` support sophisticated indexing and slicing techniques, so you can extract specific subsets of data.

7. **Array Shape Manipulation:**
 - You can reshape, transpose, and flatten `ndarrays` to suit your specific needs.



**Conclusion:**

NumPy `ndarrays` are powerful data structures in Python for work with numerical data. Their features, including multidimensionality, homogeneity, vectorization, broadcasting, and efficient memory layout, make them indispensable in large areas of scientific computing applications. Their understanding and differences with a Python list open the benefits of NumPy for your data analysis and numerical computations.


Q.6 Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans. NumPy Arrays vs. Python Lists: A Performance Showdown for Large-Scale Numerical Operations

In large-scale numerical computations in Python, using NumPy arrays over the traditional Python lists provides many worthwhile performance gains. Here's the key factors that make it so efficient:

1. Memory Efficiency:

Homogeneous Data Type:

 All elements in a NumPy array are of the same type, which makes them use less memory.

Contiguous Memory Allocation:

NumPy arrays allocate memory contiguously. This provides the possibility of very efficient access to memory and cache residency.
2. Vectorised Operations:

Broadcasting:

Operations on arrays of different shapes or sizes can be done element-wise with the help of NumPy. There is no need for any explicit loops. Due to this vectorization, computations occur significantly faster. Optimized C

Implementation :

Most NumPy operations are implemented in C to provide the necessary speed for computation compared to interpreted Python loops.
3. Advanced Mathematical Functions:

Rich Library of Mathematical Functions:

NumPy has a wide variety of mathematical functions optimized for element-wise operations in the array, including linear algebra, Fourier transforms, and statistical functions etc.

Optimized Algorithms:

Most of these are implemented with highly optimized algorithms, hence acceleration in computation.
4. Faster Indexing and Slicing:

Efficient Indexing :

Due to efficient indexing and slicing mechanisms, NumPy offers quicker access to certain elements or subarrays.

Real World Performance Comparison:

Let's consider a pretty straightforward example: multiplying two large arrays element-wise.

In [ ]:
import numpy as np
import time

# Create large Python lists
python_list1 = [i for i in range(1000000)]
python_list2 = [i * 2 for i in range(1000000)]

# Create NumPy arrays
numpy_array1 = np.arange(1000000)
numpy_array2 = numpy_array1 * 2

# Python list multiplication
start_time = time.time()
python_result = [x * y for x, y in zip(python_list1, python_list2)]
end_time = time.time()
python_time = end_time - start_time

# NumPy array multiplication
start_time = time.time()
numpy_result = numpy_array1 * numpy_array2
end_time = time.time()
numpy_time = end_time - start_time

print("Python list multiplication time:", python_time)
print("NumPy array multiplication time:", numpy_time)

Python list multiplication time: 0.5165672302246094
NumPy array multiplication time: 0.01617717742919922


Then, vectorized operations with NumPy and optimized C implementation will drastically outperform the list approach in Python as sizes of arrays grow large.

Conclusion

NumPy arrays are the preferred choice for large-scale numerical operations in Python mainly because of memory efficiency, vectorization capabilities, rich function library, and optimized implementation. Having these benefits, you can run your scientific computing workloads dramatically faster.

Q.7 Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Ans. NumPy's vstack() and hstack() functions are powerful tools for stacking arrays vertically and horizontally, respectively.

vstack()

Purpose: Stacks arrays vertically, meaning it joins them row-wise.
Syntax: np.vstack(tup)


In [ ]:
#Example:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.vstack((a, b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


hstack()

Purpose: Stacks arrays horizontally, meaning it joins them column-wise.
Syntax: np.hstack(tup)

In [ ]:
#Example:
import numpy as np

a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

c = np.hstack((a, b))
print(c)

[[1 4]
 [2 5]
 [3 6]]


Key Takeaway:

Array Shapes: The arrays to be stacked should have compatible shapes. For vstack(), the columns should be the same in number. For hstack(), the rows should be the same in number.

Data Types:

Arrays can be of different data types, but NumPy will handle type conversion automatically to ensure compatibility.

Efficiency:

Both are highly efficient for large arrays, and thus these functions are an important tool in data manipulation and analysis with NumPy.
More:

For more involved operations of stacking, use np.concatenate() which takes in arguments along which to concatenate.

On 1D arrays hstack() and vstack() are not equivalent hstack() concatenates arrays according to the first axis. while vstack() will be treating them as row vectors stacks in the vertical direction.

By knowing and using vstack() and hstack() effectively, you can efficiently manipulate and combine arrays in various data science and machine learning tasks.

Q.8 Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Ans. fliplr() vs. flipud() in NumPy

Both fliplr() and flipud() are NumPy functions used to reverse the order of elements along specific axes of an array. However, they operate on different axes:

fliplr()

1.Flips the array horizontally.

2.Reverses the order of elements along the second axis (axis=1).

3.For a 2D array, this means flipping the columns.

4.For higher-dimensional arrays, it flips the second-to-last axis.

In [ ]:
#Example:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flipped_arr = np.fliplr(arr)
print(flipped_arr)

[[3 2 1]
 [6 5 4]]


flipud()

1.Flips the array vertically.

2.Reverses the order of elements along the first axis (axis=0).

3.For a 2D array, this means flipping the rows.

4.For higher-dimensional arrays, it flips the first axis.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flipped_arr = np.flipud(arr)
print(flipped_arr)

[[4 5 6]
 [1 2 3]]


Note:

1.Both operations return a view of the original array so that no copy of the underlying data is actually made.

2.To assign new array with data flipped use np.copy().

Knowing these differences you may work with arrays in NumPy in order to accomplish most of the things you need for data processing tasks.

Q.9 Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans. NumPy's array_split() Function:

A Dive
NumPy's array_split() function is a convenient utility used for splitting an array into multiple sub-arrays. This function is highly useful in splitting an array of a certain number of sub-arrays irrespective of whether division has to be done either evenly or unevenly.

How array_split() works

INPUT

1.Array : The array to split

2.Sections : Number of desired sections

3.Splitting:

*Even Split: If the length of the array is evenly divisible by the number of sections, array_split() splits up the array into equal-sized sub-arrays.

*Uneven Split: If the division is uneven, then the extra elements are distributed among the first few sub-arrays so that the difference in sizes between sub-arrays is at most 1.

*Handling Uneven Splits:
Here is an example which shows what happens in an uneven split using array_split():

In [ ]:
import numpy as np

arr = np.arange(10)
split_arr = np.array_split(arr, 3)

print(split_arr)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


Now you can see that the first two elements in each of the sub-arrays are 3 in number, while the last one is 4. This is because 10 is not completely divisible by 3; so the remaining one is added to the last sub-array.

Important Points to Remember

1.array_split() returns an array of sub-arrays.

2.It's flexible and can take both even and uneven splits.

3.Alternatively, if you actually need more finely controlled split operations, then perhaps you want to use the split() function, which requires a list of indices that specify the splitting points.

4.Understanding how array_split() works could split NumPy arrays into smaller, easier-to-manage pieces for most data processing and analysis tasks.

Q.10  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Ans.Vectorization and Broadcasting in NumPy

NumPy is a very powerful Python library for general-purpose numerical computation, and the two techniques on which it relies to make array operations efficient are vectorization and broadcasting.

Vectorization

Vectorization is essentially an approach that replaces explicit, nested loops by optimized computations involving entire arrays at once. Since this takes proper advantage of all hardware-level optimizations, one might anticipate that NumPy would always outperform traditional Python loops and other serial approaches.

Array Operations: Many NumPy functions and operators can be used directly on arrays. For example, adding two arrays adds corresponding elements together without needing explicit loops.
Broadcasting: Broadcasting refers to allowing NumPy to perform operations on arrays with different shapes provided that are otherwise compatible. This usually occurs by implying the expansion of one or more arrays to match the other's shape.
Broadcasting Rules:

Shape Compatibility: Arrays must have compatible dimensions. If the dimensions differ, the smaller array is "stretched" or "broadcast" to match the larger one.
Dimension Compatibility: Every dimension of the arrays must be either equal or one of them must be 1.
Broadcasting Direction: Broadcasting occurs along the dimensions with size 1.

In [1]:
#Example

import numpy as np

# Create two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized addition
c = a + b  # Equivalent to [1+4, 2+5, 3+6]

# Broadcasting example
d = np.array([[1], [2], [3]])
e = np.array([4, 5, 6])

f = d + e  # d is broadcast to match the shape of e

Advantages of Vectorization and Broadcasting:

Efficiency: Without loops in Python, NumPy can take advantage of optimized C-based implementations for considerable performance boosts.
Readability: Vectorized code is usually more concise and readable, since it avoids explicit loops and complex indexing.
Memory Efficiency: Broadcasting avoids unnecessary memory copies, which makes it memory efficient.

Understanding and using vectorization and broadcasting effectively can help you write very efficient and elegant code in NumPy for a wide range of numerical computations.

**Practical Questions:**

Q.1 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
#Ans
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

print("Original array:")
print(array)

# Interchange rows and columns (transpose)
array_transposed = array.T

print("\nTransposed array:")
print(array_transposed)

Original array:
[[47 95 50]
 [45 44 58]
 [18 98 16]]

Transposed array:
[[47 45 18]
 [95 44 98]
 [50 58 16]]


Q.2  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [3]:
#Ans
import numpy as np

# Create a 1D NumPy array with 10 elements
arr = np.arange(10)
print("1D array:", arr)

# Reshape it into a 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("2x5 array:\n", arr_2x5)

# Reshape it into a 5x2 array
arr_5x2 = arr.reshape(5, 2)
print("5x2 array:\n", arr_5x2)

1D array: [0 1 2 3 4 5 6 7 8 9]
2x5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q.3  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [4]:
#Ans
import numpy as np

# Create a 4x4 array with random float values
array = np.random.rand(4, 4)

# Add a border of zeros using np.pad
array_with_border = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print(array_with_border)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.8520888  0.57477032 0.55503368 0.00497214 0.        ]
 [0.         0.55470087 0.06122647 0.46785286 0.2632445  0.        ]
 [0.         0.55580478 0.11650465 0.23800786 0.09061054 0.        ]
 [0.         0.91146984 0.94464248 0.35921099 0.2851407  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q.4 Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [5]:
#Ans.
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print(array)

[10 15 20 25 30 35 40 45 50 55 60]


Q.5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [7]:
#Ans.
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations using vectorized operations from np.char
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)

print("Original array:", arr)
print("Uppercase array:", uppercase_arr)
print("Lowercase array:", lowercase_arr)
print("Titlecase array:", titlecase_arr)

Original array: ['python' 'numpy' 'pandas']
Uppercase array: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase array: ['python' 'numpy' 'pandas']
Titlecase array: ['Python' 'Numpy' 'Pandas']


Q.6 Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [8]:
#Ans.
import numpy as np

# Create a NumPy array of words
words = np.array(["hello", "world", "numpy"])

# Insert a space between each character using np.char.join
spaced_words = np.char.join(" ", words)

print(spaced_words)

['h e l l o' 'w o r l d' 'n u m p y']


Q.7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [9]:
#Ans.
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition_result = array1 + array2
print("Addition:\n", addition_result)

# Element-wise subtraction
subtraction_result = array1 - array2
print("Subtraction:\n", subtraction_result)

# Element-wise multiplication
multiplication_result = array1 * array2
print("Multiplication:\n", multiplication_result)

# Element-wise division
division_result = array1 / array2
print("Division:\n", division_result)

Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Q.8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [11]:
#Ans.
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:")
print(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


Q.9  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [12]:
#ans.
import numpy as np

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]
print("Random Integers:", random_integers)
print("Prime Numbers:", prime_numbers)

Random Integers: [173 896 972 855 471 807 181 794 173 869 100  71  73  44 761 118 581 886
 695 973 826 728 839 130 164 726  33 353 273  91 169 962 905  84 321 462
  21 682 515 175 679 755 978  53 196 608   4 537  50 870 572 314 252 160
 968 277 398   4 201 871 616 636 376  58 849 353 267 195 709 553 580  36
 654 159 708 107 174 117 452 821 844 318 427  47 621 750 285 562 628 116
  41  39 933 423  12 295 486 848 701 264]
Prime Numbers: [173, 181, 173, 71, 73, 761, 839, 353, 53, 277, 353, 709, 107, 821, 47, 41, 701]


Q.10 . Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [14]:
#Ans.

#Ans.
import numpy as np

# Create a NumPy array representing daily temperatures for a month
daily_temperatures = np.random.randint(low=15, high=35, size=30)  # Random temperatures between 15 and 35 degrees

# Reshape the array to have 5 weeks (6 days each) to match the total of 30 days
# and calculate weekly averages
# NOTE: Adjusted the reshape to (5, 6) to accommodate 30 elements
weekly_averages = daily_temperatures.reshape(5, 6).mean(axis=1)

# Display the results
print("Daily Temperatures:", daily_temperatures)
print("Weekly Averages:", weekly_averages)

Daily Temperatures: [30 21 29 21 18 23 25 15 18 17 15 33 31 25 19 30 21 21 16 34 24 19 15 32
 29 22 27 24 30 29]
Weekly Averages: [23.66666667 20.5        24.5        23.33333333 26.83333333]
